import './sass/main.scss';
import './js/header-library';
import './js/header-library-OLD';
import './js/render-gallery';
import './js/search';
import './js/modal';
import './js/get-film-description';
import './js/pagination';
import './js/local-storage';